//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_CENTROS
    {
        public int CENTRO { get; set; }
        public string DESCRIP { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public string CLAVE_PROG { get; set; }
        public Nullable<short> NIVEL_ATENCION { get; set; }
        public Nullable<int> Tipo_Unidad { get; set; }
        public string DIRECCION { get; set; }
        public Nullable<int> entidad_id { get; set; }
        public Nullable<int> id_municipio { get; set; }
        public Nullable<int> pk_cp { get; set; }
        public string tel { get; set; }
        public string rfc { get; set; }
        public Nullable<bool> replica { get; set; }
    }
}
