//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ca_FuenteFinanciamiento
    {
        public int Id_FuenteFinanciamiento { get; set; }
        public string Descripcion { get; set; }
        public int Estatus { get; set; }
        public int U_Act { get; set; }
        public System.DateTime F_Act { get; set; }
    }
}
