//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PROVEEDORES
    {
        public short ESTADO { get; set; }
        public short GIRO { get; set; }
        public short PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
        public string CALLE { get; set; }
        public string COLONIA { get; set; }
        public string CODIGOP { get; set; }
        public string LOCALIDAD { get; set; }
        public string TEL1 { get; set; }
        public string TEL2 { get; set; }
        public string TEL3 { get; set; }
        public string FAX { get; set; }
        public string SSP { get; set; }
        public string OBSERVA { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public string rfc { get; set; }
    }
}
