//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class CA_PARTIDAS
    {
        public short RAMO { get; set; }
        public short UP { get; set; }
        public short UR { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<decimal> EJERCIDO { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
    }
}
