//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AlmacenEntity : DbContext
    {
        public AlmacenEntity()
            : base("name=AlmacenEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CA_CENTROS> CA_CENTROS { get; set; }
        public virtual DbSet<ma_articulos> ma_articulos { get; set; }
        public virtual DbSet<ma_articulos_desc_larga_tabla_corta> ma_articulos_desc_larga_tabla_corta { get; set; }
        public virtual DbSet<CA_TIPOSENT> CA_TIPOSENT { get; set; }
        public virtual DbSet<cpm_unidades> cpm_unidades { get; set; }
        public virtual DbSet<CA_PARTIDAS> CA_PARTIDAS { get; set; }
        public virtual DbSet<CA_PROGRAMAS> CA_PROGRAMAS { get; set; }
        public virtual DbSet<CA_PROVEEDORES> CA_PROVEEDORES { get; set; }
        public virtual DbSet<CA_TIPOSDOC> CA_TIPOSDOC { get; set; }
        public virtual DbSet<CA_TIPOSLIC> CA_TIPOSLIC { get; set; }
        public virtual DbSet<Ca_FuenteFinanciamiento> Ca_FuenteFinanciamiento { get; set; }
        public virtual DbSet<CA_PROGRAMAS_SALUD> CA_PROGRAMAS_SALUD { get; set; }
        public virtual DbSet<CA_UNIDADESM> CA_UNIDADESM { get; set; }
        public virtual DbSet<CA_UNIDADESP> CA_UNIDADESP { get; set; }
        public virtual DbSet<vwProveedores> vwProveedores { get; set; }
    }
}
