//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_articulos_desc_larga_tabla_corta
    {
        public string pk_articulos { get; set; }
        public string desc_larga { get; set; }
    }
}
