//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_articulos
    {
        public string PK_ARTICULOS { get; set; }
        public short TIPO { get; set; }
        public short GRUPO { get; set; }
        public short CLAVE { get; set; }
        public Nullable<int> PRESENTACION { get; set; }
        public int EXISTENCIA { get; set; }
        public Nullable<int> STOCK { get; set; }
        public Nullable<decimal> COSTO_UNIT { get; set; }
        public string CODIGOB { get; set; }
        public Nullable<int> CPM { get; set; }
        public Nullable<double> UNIDADES { get; set; }
        public Nullable<short> UNI_PRES { get; set; }
        public Nullable<short> RAMO { get; set; }
        public Nullable<short> UP { get; set; }
        public Nullable<short> UR { get; set; }
        public Nullable<short> NIVEL_ATENCION { get; set; }
        public string OBSERVA { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public Nullable<int> DONACION { get; set; }
        public Nullable<int> ACTIVO { get; set; }
        public Nullable<short> UNI_MED { get; set; }
        public string DESCRIPCION { get; set; }
        public Nullable<int> GPO { get; set; }
        public string DESC_LARGA { get; set; }
        public Nullable<int> rack { get; set; }
        public Nullable<int> pasillo { get; set; }
        public Nullable<int> nivel { get; set; }
        public Nullable<int> causes { get; set; }
    }
}
