//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBAlmacen
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwProveedores
    {
        public string id_prov { get; set; }
        public short ESTADO { get; set; }
        public short GIRO { get; set; }
        public short PROVEEDOR { get; set; }
        public string NOMBRE { get; set; }
    }
}
