//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class configuracion_unidades
    {
        public int id { get; set; }
        public Nullable<int> id_unidad { get; set; }
        public string descripcion_unidad { get; set; }
        public string director { get; set; }
        public string administrador { get; set; }
        public string encargado_medicamentos { get; set; }
        public string encargado_curacion { get; set; }
    }
}
