//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadro_general_medicamento
    {
        public int anio { get; set; }
        public int id { get; set; }
        public string cve { get; set; }
        public string descripcion { get; set; }
        public Nullable<bool> quitar { get; set; }
        public Nullable<bool> controlado { get; set; }
        public string origen_desc { get; set; }
        public Nullable<bool> origen_desierta { get; set; }
        public Nullable<bool> origen_consolidada { get; set; }
        public Nullable<bool> origen_dimesa { get; set; }
        public Nullable<bool> origen_otro { get; set; }
        public string origen_otro_desc { get; set; }
        public Nullable<bool> programa { get; set; }
        public string programa_desc { get; set; }
        public Nullable<int> hru { get; set; }
        public Nullable<int> hgt { get; set; }
        public Nullable<int> hmi { get; set; }
        public Nullable<int> hgm { get; set; }
        public Nullable<int> hgi { get; set; }
        public Nullable<int> iec { get; set; }
        public Nullable<int> ceh { get; set; }
        public Nullable<int> j1 { get; set; }
        public Nullable<int> j2 { get; set; }
        public Nullable<int> j3 { get; set; }
        public Nullable<int> uneme_colima { get; set; }
        public Nullable<int> uneme_tecoman { get; set; }
        public Nullable<int> uneme_manzanillo { get; set; }
        public Nullable<int> cara_varonil { get; set; }
        public Nullable<int> cara_femenil { get; set; }
        public Nullable<int> capasits_colima { get; set; }
        public Nullable<int> capasits_tecoman { get; set; }
        public Nullable<int> capasits_manzanillo { get; set; }
        public Nullable<int> fam { get; set; }
        public Nullable<int> total_mensual { get; set; }
        public Nullable<int> total_anual { get; set; }
        public Nullable<int> max_consolidada { get; set; }
        public Nullable<int> min_consolidada { get; set; }
        public Nullable<int> max_dimesa { get; set; }
        public Nullable<int> min_dimesa { get; set; }
        public Nullable<bool> nivel_1 { get; set; }
        public Nullable<bool> nivel_2 { get; set; }
        public string tipo_consumo { get; set; }
        public Nullable<bool> prospecta_baja { get; set; }
    }
}
