//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class cuadro_nacional_medicamento
    {
        public int anio { get; set; }
        public double id { get; set; }
        public string PROVEEDOR { get; set; }
        public string CuCOP { get; set; }
        public string GPO { get; set; }
        public string GEN { get; set; }
        public string ESP { get; set; }
        public string DIF { get; set; }
        public string VAR_ { get; set; }
        public string CVE { get; set; }
        public string DESCRIPCION { get; set; }
        public string UNIDAD { get; set; }
        public Nullable<double> CANT { get; set; }
        public string TIPO { get; set; }
        public Nullable<decimal> PRECIO { get; set; }
        public Nullable<double> CANTIDAD_MAXIMA { get; set; }
        public Nullable<double> CANTIDAD_MINIMA { get; set; }
        public Nullable<decimal> IMPORTE_MAXIMO { get; set; }
        public Nullable<decimal> IMPORTE_MINIMO { get; set; }
        public string LICITACION { get; set; }
    }
}
