//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class det_pedido
    {
        public int id_pedido { get; set; }
        public int id_unidad { get; set; }
        public int id { get; set; }
        public string PK { get; set; }
        public string cve { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> cpm { get; set; }
        public Nullable<int> existencias { get; set; }
        public Nullable<int> solicitadas { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string origen { get; set; }
        public Nullable<int> tipo { get; set; }
        public string presentacion { get; set; }
        public string subtipo_insumo { get; set; }
    }
}
