//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_inventario_dia
    {
        public int id { get; set; }
        public int id_unidad { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<int> mes { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> tipo { get; set; }
        public string hora { get; set; }
    }
}
