//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_pedido
    {
        public int id { get; set; }
        public int id_unidad { get; set; }
        public Nullable<int> anio { get; set; }
        public Nullable<int> mes { get; set; }
        public string folio { get; set; }
        public Nullable<int> tipo_pedido { get; set; }
        public string descrip_unidad { get; set; }
        public Nullable<int> claves_total { get; set; }
        public Nullable<int> claves_solicitadas { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<System.DateTime> fecha_actualiza { get; set; }
        public Nullable<System.DateTime> fecha_confirmado { get; set; }
        public Nullable<bool> pedido_confirmado { get; set; }
        public Nullable<System.DateTime> fecha_envio { get; set; }
        public string folio_almacen { get; set; }
        public Nullable<int> estatus { get; set; }
        public string pedido { get; set; }
        public Nullable<bool> controlado { get; set; }
    }
}
