//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu_Settings
    {
        public int idmodules { get; set; }
        public int idusers { get; set; }
        public string namemodules { get; set; }
        public Nullable<bool> agregar { get; set; }
        public Nullable<bool> ver { get; set; }
        public Nullable<bool> actualizar { get; set; }
        public Nullable<bool> eliminar { get; set; }
        public Nullable<int> parentmenuid { get; set; }
    }
}
