//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class modules
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modules()
        {
            this.roles_modules_privileges = new HashSet<roles_modules_privileges>();
        }
    
        public int idmodules { get; set; }
        public string codemodules { get; set; }
        public string namemodules { get; set; }
        public int parentmenuid { get; set; }
        public int ordernumber { get; set; }
        public string menuurl { get; set; }
        public string menuicon { get; set; }
        public string menuaction { get; set; }
        public string menucontrolador { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<roles_modules_privileges> roles_modules_privileges { get; set; }
    }
}
