//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PedidoEntity : DbContext
    {
        public PedidoEntity()
            : base("name=PedidoEntity")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<roles> roles { get; set; }
        public virtual DbSet<parametros_sys> parametros_sys { get; set; }
        public virtual DbSet<det_inventario_articulo> det_inventario_articulo { get; set; }
        public virtual DbSet<cuadro_nacional_medicamento> cuadro_nacional_medicamento { get; set; }
        public virtual DbSet<cuadro_general_medicamento> cuadro_general_medicamento { get; set; }
        public virtual DbSet<Menu_Settings> Menu_Settings { get; set; }
        public virtual DbSet<modules> modules { get; set; }
        public virtual DbSet<modules_temp> modules_temp { get; set; }
        public virtual DbSet<roles_modules_privileges> roles_modules_privileges { get; set; }
        public virtual DbSet<usuarios> usuarios { get; set; }
        public virtual DbSet<ma_inventario_dia> ma_inventario_dia { get; set; }
        public virtual DbSet<det_pedido> det_pedido { get; set; }
        public virtual DbSet<configuracion_unidades> configuracion_unidades { get; set; }
        public virtual DbSet<ma_pedido> ma_pedido { get; set; }
    }
}
