//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class roles_modules_privileges
    {
        public int idroles_module_privileges { get; set; }
        public Nullable<int> roles_id { get; set; }
        public Nullable<int> modules_idmodules { get; set; }
        public Nullable<bool> create_privilege { get; set; }
        public Nullable<bool> read_privilege { get; set; }
        public Nullable<bool> update_privilege { get; set; }
        public Nullable<bool> delete_privilege { get; set; }
    
        public virtual modules modules { get; set; }
        public virtual roles roles { get; set; }
    }
}
