//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBPedido
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string nombre_usuario { get; set; }
        public Nullable<int> unidad { get; set; }
        public string nombre_unidad { get; set; }
        public Nullable<int> rol { get; set; }
        public string nombre_rol { get; set; }
        public Nullable<System.DateTime> fecha_registro { get; set; }
        public Nullable<int> tipo_usuario { get; set; }
        public Nullable<bool> activo { get; set; }
    }
}
