//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class DE_CADUCIDAD
    {
        public string pk_CADUCIDADES { get; set; }
        public string pk_articulos { get; set; }
        public Nullable<short> TIPO { get; set; }
        public Nullable<short> GRUPO { get; set; }
        public Nullable<short> CLAV_MED { get; set; }
        public string LOTE { get; set; }
        public Nullable<System.DateTime> CADUCIDAD { get; set; }
        public Nullable<int> CANT_ENT { get; set; }
        public Nullable<int> CANT_SAL { get; set; }
        public Nullable<int> CANT_APARTA { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public Nullable<System.DateTime> F_INS { get; set; }
        public Nullable<short> UNI_PRES { get; set; }
        public Nullable<int> no_prog { get; set; }
        public Nullable<decimal> costo { get; set; }
        public Nullable<int> CENTRO_REQ { get; set; }
        public Nullable<int> rack { get; set; }
        public Nullable<int> pasillo { get; set; }
        public Nullable<int> nivel { get; set; }
        public int id_centro { get; set; }
    }
}
