//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class de_entradas
    {
        public int FOLIO { get; set; }
        public int ANIO { get; set; }
        public string PK_ARTICULOS { get; set; }
        public int TIPO { get; set; }
        public int GRUPO { get; set; }
        public int CLAVE { get; set; }
        public Nullable<int> PRESENTACION { get; set; }
        public Nullable<int> NO_ENTRADA { get; set; }
        public Nullable<int> CANTIDAD { get; set; }
        public decimal COSTO { get; set; }
        public Nullable<decimal> IVA { get; set; }
        public Nullable<decimal> PIVA { get; set; }
        public Nullable<int> RAMO { get; set; }
        public Nullable<int> UP { get; set; }
        public Nullable<int> UR { get; set; }
        public Nullable<int> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public Nullable<int> U_CREO { get; set; }
        public Nullable<System.DateTime> F_CREO { get; set; }
        public Nullable<bool> afectado { get; set; }
        public int id_centro { get; set; }
    }
}
