//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class ma_pedidos
    {
        public int PEDIDO { get; set; }
        public int ANIO { get; set; }
        public Nullable<int> TIPO_PEDIDO { get; set; }
        public Nullable<System.DateTime> FECHA_PEDIDO { get; set; }
        public Nullable<int> CENTRO_SOL { get; set; }
        public Nullable<bool> SALIDA_GEN { get; set; }
        public string OBSERVA { get; set; }
        public Nullable<bool> ASIGNA_CAD { get; set; }
        public Nullable<int> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public Nullable<int> U_CREO { get; set; }
        public Nullable<System.DateTime> F_CREO { get; set; }
        public Nullable<bool> Afectado { get; set; }
        public Nullable<int> No_Poliza_Sal { get; set; }
        public Nullable<int> Anio_Poliza_Sal { get; set; }
        public Nullable<bool> CANCELADO { get; set; }
        public string MOTIVO { get; set; }
        public Nullable<int> U_CANC { get; set; }
        public Nullable<System.DateTime> F_CANC { get; set; }
        public string H_CANC { get; set; }
        public Nullable<int> no_prog { get; set; }
        public Nullable<System.DateTime> F_AFEC { get; set; }
        public Nullable<bool> EXTRA { get; set; }
        public int id_centro { get; set; }
    }
}
