//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class TA_Parametros
    {
        public int INDICE { get; set; }
        public string RUTA_EXE { get; set; }
        public Nullable<short> ANIO { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public Nullable<decimal> PIVA { get; set; }
        public Nullable<int> F_UNIDADESP { get; set; }
        public Nullable<int> F_ENTRADAS { get; set; }
        public Nullable<int> F_PEDIDOS { get; set; }
        public Nullable<int> F_SALIDAS { get; set; }
        public string TITULO1 { get; set; }
        public string TITULO2 { get; set; }
        public Nullable<short> U_ACT { get; set; }
        public Nullable<System.DateTime> F_ACT { get; set; }
        public Nullable<int> F_AJUSTES { get; set; }
        public Nullable<int> F_UNIDADESM { get; set; }
        public Nullable<int> centro { get; set; }
        public Nullable<int> F_RECETAS { get; set; }
        public Nullable<int> TIPO_UNIDAD { get; set; }
        public Nullable<int> MEDICO { get; set; }
        public int id_centro { get; set; }
    }
}
