//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDispCad
    {
        public string pk_articulos { get; set; }
        public string pk_CADUCIDADES { get; set; }
        public string LOTE { get; set; }
        public string CADUCIDAD { get; set; }
        public Nullable<int> disponible { get; set; }
        public int id_centro { get; set; }
    }
}
