//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListadoEntradas
    {
        public int FOLIO { get; set; }
        public int ANIO { get; set; }
        public string tipo_entrada { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string tipo_docto { get; set; }
        public string FOLIO_DOCTO { get; set; }
        public string proveedor { get; set; }
        public int id_centro { get; set; }
        public Nullable<int> TIPO_INSUMOS { get; set; }
    }
}
