//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListadoSalidas
    {
        public int FOLIO { get; set; }
        public int ANIO { get; set; }
        public string TIPO_VALE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CENTRO_SOL { get; set; }
        public int id_centro { get; set; }
    }
}
