//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListadoEntradas
    {
        public int FOLIO { get; set; }
        public int ANIO { get; set; }
        public string tipo_entrada { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string tipo_docto { get; set; }
        public string FOLIO_DOCTO { get; set; }
        public string proveedor { get; set; }
        public int id_centro { get; set; }
        public Nullable<int> TIPO_INSUMOS { get; set; }
    }
}
