//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PedidosUnidad.Models.DBConcentradora
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwListadoSalidas
    {
        public int FOLIO { get; set; }
        public int ANIO { get; set; }
        public string TIPO_VALE { get; set; }
        public Nullable<System.DateTime> FECHA { get; set; }
        public string CENTRO_SOL { get; set; }
        public int id_centro { get; set; }
    }
}
